# Example configuration for m1f-research
# Copy to .m1f.config.yml and customize

research:
  # Workflow settings
  workflow:
    expand_queries: true        # Generate search query variations
    max_queries: 5             # Maximum expanded queries to generate
    skip_review: false         # Skip URL review interface
    crawl_depth: 0            # How many levels deep to crawl (0 = target only)
    max_pages_per_site: 10    # Maximum pages to crawl per domain
    follow_external: false    # Follow links to external domains
    generate_analysis: true   # Generate AI analysis of bundle
  
  # LLM Configuration
  llm:
    provider: claude  # claude, gemini, gemini-cli
    model: claude-3-opus-20240229
    api_key_env: ANTHROPIC_API_KEY
    temperature: 0.7
    max_tokens: 4096
  
  # For CLI tools like gemini-cli
  cli_tools:
    gemini_cli:
      command: gemini
      args: ["--model", "gemini-pro"]
  
  # Default research parameters
  defaults:
    url_count: 30
    scrape_count: 15
    timeout_range: "1-3"
    output_format: markdown
  
  # Output configuration
  output:
    directory: "./m1f/research"
    create_summary: true
    create_index: true
    bundle_prefix: "research"
    include_metadata: true
  
  # Web scraping settings
  scraping:
    timeout_range: "1-3"  # Random delay between requests (seconds)
    max_concurrent: 5
    retry_attempts: 2
    user_agents:
      - "Mozilla/5.0 (m1f-research/0.1.0) AppleWebKit/537.36"
      - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    respect_robots_txt: true
    headers:
      Accept: "text/html,application/xhtml+xml"
      Accept-Language: "en-US,en;q=0.9"
  
  # Content analysis settings
  analysis:
    relevance_threshold: 7.0    # Minimum relevance score (0-10)
    duplicate_threshold: 0.8    # Similarity threshold for duplicates
    min_content_length: 100     # Minimum content length in characters
    max_content_length: 50000   # Maximum content length
    prefer_code_examples: false # Prioritize content with code
    prioritize_recent: true     # Prefer newer content
    language: "en"              # Content language preference
  
  # Research templates for different use cases
  templates:
    # Technical documentation and implementation
    technical:
      description: "Focused on implementation details and code examples"
      sources: ["web", "github"]
      analysis_focus: "implementation"
      url_count: 40
      scrape_count: 20
      analysis:
        prefer_code_examples: true
        relevance_threshold: 6.5
        min_content_length: 200
    
    # Academic and theoretical content
    academic:
      description: "Academic papers, theory, and research"
      sources: ["web", "arxiv"]
      analysis_focus: "theory"
      url_count: 25
      scrape_count: 12
      analysis:
        prefer_code_examples: false
        prioritize_recent: false
        relevance_threshold: 8.0
    
    # Step-by-step tutorials
    tutorial:
      description: "Tutorials, guides, and how-tos"
      sources: ["web", "youtube"]
      analysis_focus: "practical"
      url_count: 30
      scrape_count: 15
      analysis:
        prefer_code_examples: true
        min_content_length: 500
        relevance_threshold: 7.0
    
    # Quick overview
    quick:
      description: "Fast research with fewer sources"
      sources: ["web"]
      url_count: 10
      scrape_count: 5
      analysis:
        relevance_threshold: 8.0

# Example source configurations (for future multi-source support)
sources:
  web:
    enabled: true
    weight: 0.4
    search_engines: ["google", "bing", "duckduckgo"]
  
  github:
    enabled: false
    weight: 0.3
    token_env: GITHUB_TOKEN
    include_issues: true
    include_discussions: true
  
  arxiv:
    enabled: false
    weight: 0.2
    categories: ["cs.AI", "cs.LG", "cs.SE"]
  
  youtube:
    enabled: false
    weight: 0.1
    min_duration: 300  # 5 minutes
    include_transcripts: true